---
title: "Descriptives"
author: "Marcel Ramos"
date: "January 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
suppressPackageStartupMessages({
    library(broom)
    library(dplyr)
    library(tidyr)
    library(readr)
    library(readxl)
})
```

## Load required packages

```{r, eval = FALSE}
library(broom)
library(dplyr)
library(tidyr)
library(readr)
library(readxl)
```

## Load the dataset

```{r}
pregint <- read.csv("../data/pregint.csv")
codebookCode <- read_csv("../docs/codebookCode.csv")
recodebook <- read_excel("../docs/recodeBook.xlsx")
vardesctab <- read.table("../data/surveyvariables.txt", header = TRUE)
```

## Filter variables

Separate variable names that should not be used:

```{r}
ignoreVars <- c("ResponseID", "StartDate", "EndDate", "Finished",
    "SC0_0", "SC0_1", "SC0_2", "rid", "gc", "term", "LocationLatitude",
    "LocationLongitude", "LocationAccuracy", "states", "region",
    grep("TEXT", names(pregint), fixed = TRUE, value = TRUE), "Q1.1a",
    "Q1.1b")
## Remove Q3.17a, the select all that apply question that was intended
## as single select

keeps <- !names(pregint) %in% ignoreVars

keepnames <- names(pregint)[keeps]
```

Filter variables that have been recoded:

```{r}
pregintDESC <- pregint[, keeps]
pregintDESC <- pregintDESC[, !vapply(pregintDESC, function(x)
    all(is.na(x)), logical(1L))]
```

## Load helper functions for creating summaries

```{r}
source("../R/table-helpers.R")
```

## Summary

```{r}
alldatnames <- names(pregintDESC)
idxVec <- seq_along(pregintDESC)
names(idxVec) <- names(pregintDESC)
descres <- lapply(idxVec, function(i, dataset) {
    varname <- alldatnames[[i]]
    if (is.integer(dataset[[i]]) || is.numeric(dataset[[i]])) {
        resx <- .meansd(dataset[[i]], varName = varname)
        cbind(resx, .validperc(dataset[[i]]))
    } else if (is.factor(dataset[[i]]))
        rbind(.prop(dataset[[i]]), .validsum(dataset[[i]]))
}, dataset = pregintDESC)

resTables <- lapply(idxVec, function(i, listset) {
    x <- listset[[i]]
    varname <- alldatnames[[i]]
    rex <- cbind(rownames(x), x)
    colnames(rex)[1] <- varname
    rownames(rex) <- NULL
    cname <- colnames(rex)[[1L]]
    cname <- vapply(strsplit(cname, "_"), `[`, character(1L), 1L)
    qchar <- vardesctab[cname == vardesctab[, "item"], "description"]
    qtem <- .wrapItem(rex, as.character(qchar))
    cbind(rex, question = qtem)
}, listset = descres)
```

```{r}
file.remove("../docs/descriptives.csv")
invisible(suppressMessages({
    lapply(idxVec,  function(i, listset) {
        write.table(rbind(listset[[i]], rep("", ncol(listset[[i]]))),
            file = "../docs/descriptives.csv",
            append = TRUE, sep = ",", row.names = FALSE)
    }, listset = resTables)
}))
```

